[tool.black]
line-length = 79

[tool.isort]
line_length = 79
profile = "black"


[tool.mypy]
plugins = ["pydantic.mypy"]
follow_imports = "skip"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"